### PR TITLE
added `redemrp:TempLoadCharacter`

### PR DESCRIPTION
**Pull request by abdulkadiraktas**

### CODE REVIEW

**Comment by 919design** [comment]
Can you elaborate on the purpose of this code and why it would benefit RedEM:RP to have a net-accessible event to load a character and then unload it after 3 seconds?

**Comment by abdulkadiraktas** [comment]
I added nickname changes before selecting character. So I need `temploadcharacter` function.

https://cdn.discordapp.com/attachments/1039909052278378496/1102762219638378608/image.png

**Comment by 919design** [comment]
While I appreciate the contribution, this seems like a rather niche use case and I think you would be better off querying SQL directly rather than creating a player object for this use case.

If it works for you, use it in your version of RedEM:RP - but I can't in good faith see this being useful to anyone else, especially with a hardcoded 3000 ms wait, which already introduces a race condition straight off the bat.

**Comment by abdulkadiraktas** [comment]
Someone may need a tempload like me. This temporary load does not contain any changes to the overall code structure. So merging or not merging this PR doesn't change anything.

**Comment by 919design** [comment]
> Someone may need a tempload like me. This temporary load does not contain any changes to the overall code structure. So merging or not merging this PR doesn't change anything.

Merging this PR adds code that is not only not necessary, but it introduces a race condition if used, which was my main point.

As I said, to change the name of a player at the multicharacter screen, you should probably be using SQL directly and not loading a player object. That was not how the framework was meant to be used.

If it works for you, go ahead and use it, but this will not be useful to anyone else.

**Pull request closed without merging**
